### ISSUE TITLE
Support for PHP 8.1

### ISSUE THREAD

**Issue by giorgiopogliani** [giorgiopogliani/twig-components#16]

**Comment by majermi4** [comment]
I'm using PHP 8.1 now and haven't noticed any problems so far. Is there something known we should be aware of? :)

**Comment by giorgiopogliani** [comment]
Hey @majermi4! Actually no, it's just not tested, it was more of a reminder than an issue. 

If you didn't find any problem I will just add PHP 8.1 in the pipelines tests and we should be good.
