### ISSUE TITLE
Usage with Symfony ?

### ISSUE THREAD

**Issue by barberob** [giorgiopogliani/twig-components#17]
Hello, thanks for your awesome work !
I'm sorry if this is obvious, but i'm trying to use this with a symfony 6 app and i have no idea how to configure this package...

Since twig is somehow autoloaded by symfony I don't how to use the configuration snippet you provide (where and how ?)
```php
/** @var \Twig\Environment $twig */

use Performing\TwigComponents\Configuration;

Configuration::make($twig)
    ->setTemplatesPath('/relative/directory/to/components')
    ->setTemplatesExtension('twig')
    ->useCustomTags()
    ->setup();
```

**Comment by TLBStudioLtd** [comment]
Same - also looking for info on how to add this to a Symfony app.

**Comment by majermi4** [comment]
This is how ;-)![image](https://user-images.githubusercontent.com/2118173/200681888-9e2eb537-c6d6-4bd1-b20a-1c8a446b9ad5.png)

**Comment by TLBStudioLtd** [comment]
Cracking - thanks

**Comment by giorgiopogliani** [comment]
Thanks @majermi4! Maybe we can add that to the readme, does the example work only for Symfony 6?

**Comment by majermi4** [comment]
@giorgiopogliani The exact syntax I posted should work since Symfony 5.1 
https://symfony.com/blog/new-in-symfony-5-1-simpler-service-decoration 

With small adjustment, this should work in all versions since 2.7.

services.yaml
```
services:
        My\Namespace\TwigEnvironmentConfigurator:
                decorates: 'twig.configurator.environment'
                arguments: [ '@My\Namespace\TwigEnvironmentConfigurator.inner' ]
```

TwigEnvironmentConfigurator.php
```
use Symfony\Bundle\TwigBundle\DependencyInjection\Configurator\EnvironmentConfigurator;
use Twig\Environment;
use Performing\TwigComponents\Configuration;

final class TwigEnvironmentConfigurator
{
    public function __construct(private EnvironmentConfigurator $decorated)
    {
    }

    public function configure(Environment $environment) : void
    {
        $this->decorated->configure($environment);
    
        $relativePath = '_components'; // TODO: Change this to where you like to put your components.
        Configuration::make($environment)
            ->setTemplatesPath($relativePath)
            ->setTemplatesExtension('twig')
            ->useCustomTags()
            ->setup();
    }
}
```

**Comment by barberob** [comment]
@majermi4 works like a charm. thanks for the help !
