### ISSUE TITLE
Component file names

### ISSUE THREAD

**Issue by sjelfull** [giorgiopogliani/twig-components#2]
How would you handle filenames with `kebab-case` filenames, eg `page-header.twig`?

Is Twig nodes always lowercase?

**Comment by giorgiopogliani** [comment]
At the moment a file name like that will not work because twig tags cannot have the `-` character. It should be possible to convert names to camel case and everything should work.

**Comment by giorgiopogliani** [comment]
Fixed on 0.0.6

**Comment by sjelfull** [comment]
That's great, thank you!

Digging the plugin, and thankful you wrote it. I've been thinking about something like this for a long time, and currently I'm converting a React based site to Craft, so this is mostly perfect.
