### ISSUE TITLE
Dynamic Components

### ISSUE THREAD

**Issue by Pindagus** [giorgiopogliani/twig-components#24]
I would like something like this: https://laravel.com/docs/11.x/blade#dynamic-components

I have been trying to get this to work by detecting and replacing the component name [here](https://github.com/giorgiopogliani/twig-components/blob/9755a628b629c80c436904055502ff938d2db9cf/src/TokenParser/ComponentTokenParser.php#L69), but I can't figure out how to get this to work with a variable.

---

So this is easy to get working:
```
<x-dynamic-component :component="'test-component'" class="bg-red px-2">
    <p>Lorem ipsum</p>
</x-dynamic-component>
```
By getting the `component` value from the variables.

---

But this I can't figure out:
```
{% set componentName = 'test-component' %}
<x-dynamic-component :component="componentName" class="bg-red px-2">
    <p>Lorem ipsum</p>
</x-dynamic-component>
```
Because the `component` is a variable which resolves on compile, but in this case it is needed before compile to get the path of the actual component.

Anyone who has a thought on this?

**Comment by giorgiopogliani** [comment]
You would need to check if the component name is `dynamic-component` or maybe just `component` for short.

I think you could do something here:
https://github.com/giorgiopogliani/twig-components/blob/9755a628b629c80c436904055502ff938d2db9cf/src/Node/ComponentNode.php#L73-L76

In the function you should check when to use the variable `component` from the `$context` at runtime or keep the current behaviour. This function normally will just return the path of the component, in this case it would be `component` or `dynamic-component`. Update the path from `/component.twig` to `'/' . $context['component'] . '.twig'` and should work.
