### ISSUE TITLE
Subfolders (namespaces)

### ISSUE THREAD

**Issue by sjelfull** [giorgiopogliani/twig-components#3]
Have you considered adding support for namespaces or subfolders?

An example: I'm making a bunch of components called `intro` or `header` that lives in different contexts and often are very different.

Thus I want to group them in subfolders, say `blog/intro.twig`, `faq/intro.twig` etc.

Would it make sense to add support for prefixes to `ComponentTokenParser`, and then use the folder structure as a prefix?

Say, something like `blogIntro`, `faqIntro` etc.? If you nest folders, it would just keep adding it.

So if you have `blog/view/intro.twig` that would turn into `blogViewIntro`.

**Comment by giorgiopogliani** [comment]
I thought about this but I don't _really_ like it.

Also files like `blog-intro.twig` are converted to `blogIntro` tokens, so adding this can be ambiguous.

I also thought about change the syntax in order to better manage things. What do you think?
```twig
{% x 'blog.intro' %}
...
{% endx %}
```

**Comment by sjelfull** [comment]
Aha, that is a fair point. 

Yeah, something like that could also be nice. Not sure if the single quotation marks is as nice to type. 

What about something like `{% x:blog.intro %}`, similar to [Blade components](https://laravel.com/docs/8.x/blade#displaying-components)?

**Comment by giorgiopogliani** [comment]
Well, I just did some tests and this could work!

I should just think how handle tokens like `-` and `_` or other special tokens. Because without the quotes everything becomes a twig token. I guess it's ok to just allow `-` and `_` and skip everything else, with the `.` be the only separator.

**Comment by sjelfull** [comment]
I agree, that sounds like a solid solution.
