### ISSUE TITLE
TwigComponents

### ISSUE THREAD

**Issue by ostark** [giorgiopogliani/twig-components#4]
I actually started a very similar project https://github.com/TwigComponents one day before your first commit ;-)
You are still ahead since your code is open source, mine isn't.

Is there any reason why you stuck with the 0.1.0 release?

**Comment by giorgiopogliani** [comment]
Hi! There are some tests and the plugin works, but there are some things that I may want to change. Also I would like to improve the code and wait to have general feeling that it's good before tag the `1.0` (e.g. remove the `raw` filter to output the slots and attributes).

**Comment by ostark** [comment]
TBH, I like the `{% x:foo %}` more than `{% component "foo" %}` syntax, but at the end of the day the html-ish syntax makes most sense to be in sync with Laravel/blade and to support IDE autocompletion.

**Comment by giorgiopogliani** [comment]
Yes, the html-ish it's the one I wanted, I didn't find a way to tap in the html before the parsing. Do you think we can merge our work?

**Comment by ostark** [comment]
This is probably needed to get rid of the ` | raw` filter:
https://github.com/TwigComponents/extension/blob/master/src/ComponentExtension.php#L23-L26

I can not fully remember what I did and why. I haven't touched the code for 3 months.

the similarities are funny ...

**Comment by ostark** [comment]
> Do you think we can merge our work?

I think it makes sense.

---

I created a GH organization because  I had something big in mind :-) - with component libraries and integrations for Symfony, Drupal, Craft and what not ...

I also did a Livewire/twig prototype - but that's another story  ;-)
